### PR TITLE
Use unified memory for scalar indexing of permutation matrices

### PR DESCRIPTION
**Pull request by tgymnich**

### CODE REVIEW

**Comment by tgymnich** [comment]
How should we approach doing the same for scalar indexing inside of GPUArrays.jl?

**Comment by maleadt** [comment]
I recently reworked indexing in GPUArrays to make exactly this possible, see https://github.com/JuliaGPU/GPUArrays.jl/pull/499 and https://github.com/JuliaGPU/CUDA.jl/pull/2138 for an implementation.

**Review by christiangnrd — APPROVED** [review]
This looks good to me.

Does this include scalar indexing inside of GPUArrays.jl? if not should an issue be filed so we don't forget to eventually get to it?

I also noticed some stuff that's not really in the scope of this PR so I'll submit a separate one.

**Comment by maleadt** [comment]
> Does this include scalar indexing inside of GPUArrays.jl? If not, should an issue be filed so we don't forget to eventually get to it?

https://github.com/JuliaGPU/Metal.jl/issues/443

**Pull request merged**
