### PR TITLE
Implement atomics using compiler intrinsics

### PR DESCRIPTION
**Pull request by maleadt**
Fixes https://github.com/JuliaGPU/Metal.jl/issues/79
Depends on https://github.com/JuliaGPU/GPUCompiler.jl/pull/436, https://github.com/JuliaGPU/Metal.jl/pull/169

Doesn't contain all low-level atomics yet, and still needs some high-level magic on top of that (i.e. `@atomic`).

### CODE REVIEW

**Comment by maleadt** [comment]
From looking at CI, looks like this doesn't work on macOS 12.

**Comment by christiangnrd** [comment]
> From looking at CI, looks like this doesn't work on macOS 12.

Could it be related to Float atomics only being supported starting with Metal 3?

**Comment by maleadt** [comment]
Ah yes I overlooked that. Let's try.

**Comment by maleadt** [comment]
Interesting failure:

```julia
function kernel(a)
    i = thread_position_in_threadgroup_1d()

    # load device memory into threadgroup on first thread
    b = MtlThreadGroupArray(Int32, 1)
    if i == 1
        #Metal.@atomic b[1] = 0
        Metal.atomic_store_explicit(pointer(b, 1), Int32(0))
    end

    threadgroup_barrier(Metal.MemoryFlagThreadGroup)

    # atomically increment threadgroup memory by every thread
    #Metal.@atomic b[1] += 1
    Metal.atomic_fetch_add_explicit(pointer(b, 1), Int32(1))

    threadgroup_barrier(Metal.MemoryFlagThreadGroup)

    # have first thread sync back to device memory
    if i == 1
        #a[1] = Metal.@atomic b[1]
        a[1] = Metal.atomic_load_explicit(pointer(b, 1))
    end

    return
end

# launch kernel and show results
a = MtlArray(Int32[0])
@metal threads=100 kernel(a)
```

This should make `a[1] == 100`, but it consistently returns 69 when accessing the value from thread 1. Smells like a compilation bug in the back-end.

**Pull request merged**
