### PR TITLE
Do not change grain size after pipeline creation

### LINKED ISSUE #132: mapreduce kernel uses too many threads
I'm getting some errors on 1.9-rc1 on my M2 Max device that I can't reproduce on M1 (on main branch).

`gpuarrays/reductions/== isequal` has 242 passing tests and 6 that error with the exact same error shown below. 

I was able to identify the failing tests to be lines 188 and 191 in `GPUArrays.jl/test/testsuite/reductions.jl`, only for `ET in [Int16, Int32, Int]` and when `sz == (10,10,10)`

When I manually reverted #112 to keep the other changes to main, the errors went away.

```
Error in testset gpuarrays/reductions/== isequal:
Error During Test at /Users/christian/.julia/packages/GPUArrays/6STCb/test/testsuite/reductions.jl:170
  Test threw exception
  Expression: compare(((A, B)->begin
            isequal(A, B)
        end), AT, rand(range, sz), rand(range, sz))
  ArgumentError: Number of threads in group (832) should not exceed 768
  Stacktrace:
    [1] (::Metal.HostKernel{typeof(Metal.partial_mapreduce_device), Tuple{typeof(identity), typeof(&), Bool, Val{0x0000000000000340}, Val{CartesianIndices((10, 10, 10))}, Val{CartesianIndices((1, 1, 1))}, Val{0x0000000000000001}, Val{2}, Val{false}, MtlDeviceArray{Bool, 4, 1}, Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{3}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(isequal), Tuple{MtlDeviceArray{Int64, 3, 1}, MtlDeviceArray{Int64, 3, 1}}}}})(::Function, ::Vararg{Any}; groups::Int64, threads::UInt64, queue::Metal.MTL.MTLCommandQueueInstance)
      @ Metal ~/.julia/packages/Metal/J1c82/src/compiler/execution.jl:201
    [2] macro expansion
      @ ~/.julia/packages/Metal/J1c82/src/compiler/execution.jl:66 [inlined]
    [3] mapreducedim!(f::typeof(identity), op::typeof(&), R::MtlArray{Bool, 3}, A::Base.Broadcast.Broadcasted{Metal.MtlArrayStyle{3}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(isequal), Tuple{MtlArray{Int64, 3}, MtlArray{Int64, 3}}}; init::Bool)
      @ Metal ~/.julia/packages/Metal/J1c82/src/mapreduce.jl:224
    [4] _mapreduce(::typeof(isequal), ::typeof(&), ::MtlArray{Int64, 3}, ::MtlArray{Int64, 3}; dims::Colon, init::Bool)
      @ GPUArrays ~/.julia/packages/GPUArrays/6STCb/src/host/mapreduce.jl:69
    [5] _mapreduce
      @ ~/.julia/packages/GPUArrays/6STCb/src/host/mapreduce.jl:35 [inlined]
    [6] #mapreduce#31
      @ ~/.julia/packages/GPUArrays/6STCb/src/host/mapreduce.jl:31 [inlined]
    [7] mapreduce
      @ ~/.julia/packages/GPUArrays/6STCb/src/host/mapreduce.jl:31 [inlined]
    [8] isequal
      @ ~/.julia/packages/GPUArrays/6STCb/src/host/mapreduce.jl:110 [inlined]
    [9] (::Main.TestSuite.var"#290#303")(A::MtlArray{Int64, 3}, B::MtlArray{Int64, 3})
      @ Main.TestSuite ./none:0
   [10] compare(::Function, ::Type{MtlArray}, ::Array{Int64, 3}, ::Vararg{Array{Int64, 3}}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ Main.TestSuite ~/.julia/packages/GPUArrays/6STCb/test/testsuite.jl:44
   [11] compare(::Function, ::Type{MtlArray}, ::Array{Int64, 3}, ::Vararg{Array{Int64, 3}})
      @ Main.TestSuite ~/.julia/packages/GPUArrays/6STCb/test/testsuite.jl:38
   [12] macro expansion
      @ ~/.julia/juliaup/julia-1.9.0-rc1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/Test/src/Test.jl:478 [inlined]
   [13] macro expansion
      @ ~/.julia/packages/GPUArrays/6STCb/test/testsuite/reductions.jl:170 [inlined]
   [14] macro expansion
      @ ~/.julia/juliaup/julia-1.9.0-rc1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.9/Test/src/Test.jl:1586 [inlined]
   [15] (::Main.TestSuite.var"#286#299")(AT::Type, eltypes::Vector{DataType})
      @ Main.TestSuite ~/.julia/packages/GPUArrays/6STCb/test/testsuite/reductions.jl:160

```

### PR DESCRIPTION
**Pull request by maxwindiff**
Don't change grain size after pipeline creation, otherwise the maximum allowed number of threads may change, and launch parameters could be invalidated. When calculating the grain size, assume 1024 threads will be launched, which is on the conservative side (i.e. will tend to use a smaller grain size), but there should be no harm. On the plus side, the extra compilation is eliminated, so it runs slightly faster in some cases.

Before: https://gist.github.com/maxwindiff/dcb8f3bcc926cbfc3ef55940fd35f345
After: https://gist.github.com/maxwindiff/f4c361e12b738ccd21c9a96768b9501d

Alternatives considered:
* Pass grain size as a normal integer instead of a `Val`. Unfortunately this slows things down by quite a bit (10-40%).
* Iteratively calculate grain size and thread count until they converge. Not chosen since this wastes too many compilations.

Fixes #132

### CODE REVIEW

**Comment by maleadt** [comment]
> it can change between kernel setup and launch, and pipeline parameters computed at setup time may be invalid during run time

Can't you keep the grain size stable? Or only change it in a way that won't affect (or only increase) the amount of threads that can be launched?

**Comment by maxwindiff** [comment]
> Or only change it in a way that won't affect (or only increase) the amount of threads that can be launched?

The number of threads won't change actually, the [adjustment here](https://github.com/JuliaGPU/Metal.jl/blob/main/src/mapreduce.jl#L213) only affects the number of groups. I think what happened is that changing the grain size also changes the generated code, which somehow resulted in a smaller `maxTotalThreadsPerThreadgroup`.

> Can't you keep the grain size stable? 

Let me think a bit more... maybe there's a way to calculate a upper or lower bound somehow.

**Comment by maleadt** [comment]
> > Or only change it in a way that won't affect (or only increase) the amount of threads that can be launched?
> 
> The number of threads won't change actually, the [adjustment here](https://github.com/JuliaGPU/Metal.jl/blob/main/src/mapreduce.jl#L213) only affects the number of groups. I think what happened is that changing the grain size also changes the generated code, which somehow resulted in a smaller `maxTotalThreadsPerThreadgroup`.

I know; what I meant is that if you know the impact of changing `grain` you could change it in a direction that won't decrease the max thread count. However, that's probably fragile, so using a fixed grainsize seems like the only realistic option.

It would also be possible to iterate (change grain size, compile, check if max thread count changed), but that is extremely wasteful in terms of compilation. Now already we actually compile two kernels for each `mapreduce` invocation, so that's another argument for a fixed grainsize.

**Comment by maxwindiff** [comment]
Yep took your suggestion and used a fixed grainsize. This also saves a compilation. PTAL!

**Review by maleadt — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
