### PR TITLE
Add more tests to api validation testing

### PR DESCRIPTION
**Pull request by christiangnrd**
Not worth running a test we know will fail with only one apple silicon runner.

### CODE REVIEW

**Comment by christiangnrd** [comment]
Right this is still broken on Ventura.

**Comment by christiangnrd** [comment]
All tests can now be run with the shader validation enabled except for `device_code_agx` for which I've opened #463!

**Review by maleadt — APPROVED** [review]

**Comment by maleadt** [comment]
At some point we should device and audit whether to check for non-zero length as part of each API call (e.g., `unsafe_fill!` here), or only from the high-level caller. It's a bit messy to have these `N > 0` calls all over the place. For `fill!`, the high-level caller already does so: https://github.com/JuliaGPU/Metal.jl/blob/711758d725da0a6783bf42d7908534c0f807cb7e/src/array.jl#L534-L540

**Comment by christiangnrd** [comment]
> At some point we should device and audit whether to check for non-zero length as part of each API call (e.g., `unsafe_fill!` here), or only from the high-level caller. It's a bit messy to have these `N > 0` calls all over the place. For `fill!`, the high-level caller already does so:
> 
> https://github.com/JuliaGPU/Metal.jl/blob/711758d725da0a6783bf42d7908534c0f807cb7e/src/array.jl#L534-L540

That's from a recent PR where I tried to address some validation errors. I can remove the high-level change since it wasn't enough and leave the low-level one in #464

**Pull request merged**
