### PR TITLE
Switch CI to 1.11.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by christiangnrd** [comment]
Should we also revert 71b784ec9d6adf8a758e4d77f3b12ed53e7cea34?

**Comment by maleadt** [comment]
> Should we also revert [71b784e](https://github.com/JuliaGPU/Metal.jl/commit/71b784ec9d6adf8a758e4d77f3b12ed53e7cea34)?

Yeah, sure. Is that the reason for the compilation failure? I thought I had fixed the underlying issues, https://github.com/JuliaGPU/Metal.jl/issues/370#issuecomment-2306832755.

**Comment by maleadt** [comment]
Something wrong with the debug info:

```
      "frames": [
        {
          "imageOffset": 56140,
          "symbol": "__abort_with_payload",
          "symbolLocation": 8,
          "imageIndex": 1
        },
        {
          "imageOffset": 212612,
          "symbol": "abort_with_payload_wrapper_internal",
          "symbolLocation": 104,
          "imageIndex": 1
        },
        {
          "imageOffset": 212508,
          "symbol": "abort_with_reason",
          "symbolLocation": 32,
          "imageIndex": 1
        },
        {
          "imageOffset": 598872,
          "symbol": "fatalErrorHandler(void*, char const*, bool)",
          "symbolLocation": 724,
          "imageIndex": 8
        },
        {
          "imageOffset": 24336744,
          "symbol": "llvm::report_fatal_error(llvm::Twine const&, bool)",
          "symbolLocation": 412,
          "imageIndex": 9
        },
        {
          "imageOffset": 30557624,
          "symbol": "llvm::report_fatal_error(char const*, bool)",
          "symbolLocation": 52,
          "imageIndex": 9
        },
        {
          "imageOffset": 12603572,
          "symbol": "llvm::UpgradeDebugInfo(llvm::Module&)",
          "symbolLocation": 452,
          "imageIndex": 9
        },
```

**Comment by maleadt** [comment]
Looks like the IR downgrader is messing up the IR.

**Comment by maleadt** [comment]
MWE:

```llvm
define void @kernel() {
top:
  store ptr addrspace(1) null, ptr null, align 8
  br label %block

block:
  %in = phi ptr [ null, %top ]
  ret void
}
```

The problem is that the downgrader inserts bitcasts _before_ the phi:

```llvm
define void @kernel() {
top:
  %0 = bitcast ptr null to ptr
  store ptr addrspace(1) null, ptr %0, align 8
  br label %block

block:                                            ; preds = %top
  %1 = bitcast ptr null to ptr
  %in = phi ptr [ %1, %top ]
  ret void
}
```

**Comment by maleadt** [comment]
https://github.com/JuliaGPU/llvm-downgrade/commit/4ebc423a3c9760fbb8dd58724966e75e0a66f8a2

**Pull request merged**
