### PR TITLE
Handle missing adjoint case.

### PR DESCRIPTION
**Pull request by maleadt**
cc @dkarrasch

### CODE REVIEW

**Comment by dkarrasch** [comment]
I was wondering about that, but I thought that maybe only real eltypes are allowed. Also, transpose multiplication fails over at GPUArrays.jl for Metal.jl. Isn't matrix multiplication tested here?

**Comment by maleadt** [comment]
> Also, transpose multiplication fails over at GPUArrays.jl for Metal.jl. Isn't matrix multiplication tested here?

We rely on the GPUArrays test suite to cover that (which is run as part of the CI here). The MPS tests in this repository only test nonstandard features.

**Comment by maleadt** [comment]
> I was wondering about that, but I thought that maybe only real eltypes are allowed.

Interestingly, `t = 'C'` seems to be used for Float16 eltypes.

**Comment by maleadt** [comment]
Ah, looks like before #186 we weren't actually using MPS for transpose matmul, and something seems wrong here indeed. Let me debug this.

**Pull request merged**
